### ISSUE TITLE
 入力内容	備考 【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by mayu1122oo** [mayu1122oo/protospace-39068#1]
# URL
https://protospace-39068.onrender.com/

**Comment by motomuun** [comment]
@mayu1122oo さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ一覧表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
プロトタイプのタイトルをクリックしても、詳細ページへ遷移できません。タイトルからも遷移できるように修正をお願いします。

**プロトタイプ編集機能**

- [x] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空のフォームがある状態で「保存する」を押すと、全てのフォームが空になってしまいます。入力済みの項目(フォーム)は消えないように修正をお願いします。

**ユーザー詳細機能**

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
投稿したプロトタイプ画像が表示されるように修正をお願いします。
<img width="1025" alt="スクリーンショット 2023-03-15 9 17 16" src="https://user-images.githubusercontent.com/65059944/225170763-e568601f-4a24-4b73-87b9-fa334dc97b9d.png">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mayu1122oo** [comment]
修正いたしました。
ご確認のほど、よろしくお願いいたします。

**Comment by motomuun** [comment]
@mayu1122oo さん、再度ご提出頂きありがとうございます‼︎
動作の確認をしたところ、一点だけ修正していただきたい箇所がございました。
今一度、以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [ ]  **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空のフォームがある状態で「保存する」を押すと、全てのフォームが空になってしまいます。入力済みの項目(フォーム)は消えないように修正をお願いします。

https://user-images.githubusercontent.com/65059944/225217552-8539b521-32c0-4498-8c0a-6b851d7f29b4.mov




修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mayu1122oo** [comment]
ご確認いただきありがとうございます。
こちらで確認しましたところ、入力済のフォームはそのまま残っているのですが今一度ご確認いただけますでしょうか。
お手数をおかけいたしますが、よろしくお願いいたします。
↓挙動のGifを作成いたしました。


https://user-images.githubusercontent.com/126050677/225219517-ddc2b65f-fd35-4932-82b3-1a549c990cf0.mp4

**Comment by shodai-ito** [comment]
@mayu1122oo さん、コメントありがとうございます。
いただいた動画は新規投稿の挙動かと存じますが、指摘させていただきましたのは編集の挙動となっております。
編集画面での挙動をキャプチャしましたのでご確認いただけますと幸いです。

https://user-images.githubusercontent.com/62537107/225219671-63239f1c-f171-4022-ad7b-250376631ac8.mov

**Comment by mayu1122oo** [comment]
ご確認ありがとうございます。
きちんと内容の確認ができておらず、申し訳ございません。
ご指摘いただいた箇所の修正を行いましたので、ご確認のほどよろしくお願いいたします。

**Comment by shodai-ito** [comment]
@mayu1122oo さん、修正の上ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by mayu1122oo** [comment]
ご確認いただきありがとうございます。
LGTMうれしいです！

引き続き頑張ります！
